# -*- coding: utf-8 -*-
"""HW3 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zd-YIriwBcMGh6W71NnXgVaMytdw3KHm

# ============================================================
# Real vs. Fake Job Posting Detection
# ============================================================
# Dataset: "Real or Fake? Fake Job Posting Prediction"
# Source: https://www.kaggle.com/datasets/shivamb/
#
# Task: Binary text classification
#   Predict whether a job posting is fraudulent (1) or legitimate (0)
#
# Three approaches:
#   1. Baseline     - TF-IDF + Logistic Regression
#   2. Approach A   - Fine-tuned DistilBERT
#   3. Approach B   - DistilBERT as feature extractor + Logistic Regression
# ============================================================
"""
# Colab only:
# !pip install -q transformers kagglehub accelerate

# ── Imports ───────────────────────────────────────────────────────────────────
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    DistilBertModel,
    get_linear_schedule_with_warmup,
)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
    roc_auc_score,
)

import kagglehub


# download the dataset from kaggle and load it into a dataframe
path = kagglehub.dataset_download("shivamb/real-or-fake-fake-jobposting-prediction")
csv_path = os.path.join(path, "fake_job_postings.csv")
df = pd.read_csv(csv_path)

print(f"Dataset shape: {df.shape}")
print(df["fraudulent"].value_counts())
print(df["fraudulent"].value_counts(normalize=True).round(3))


# some of the text columns have missing values so I fill them with empty strings
# then Ismash all the text columns together into one big string per posting
text_cols = ["title", "company_profile", "description", "requirements", "benefits"]
for col in text_cols:
    df[col] = df[col].fillna("")

df["combined_text"] = (
    df["title"] + " " +
    df["company_profile"] + " " +
    df["description"] + " " +
    df["requirements"] + " " +
    df["benefits"]
)

# X is our input text, y is what we're trying to predict (0 = real, 1 = fake)
X = df["combined_text"]
y = df["fraudulent"]

# 80/20 split, stratify makes sure both splits have the same ratio of fake to real
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTrain size: {len(X_train)}  |  Test size: {len(X_test)}")


# quick EDA to get a feel for the data before modeling
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# first plot just shows how imbalanced the classes are — way more real postings than fake
counts = y.value_counts().sort_index()
bars = axes[0].bar(["Legitimate", "Fraudulent"], counts.values, color=["#4C9BE8", "#E8654C"])
axes[0].set_ylabel("Count")
axes[0].set_title("Class Distribution")
for bar, val in zip(bars, counts.values):
    axes[0].text(bar.get_x() + bar.get_width() / 2,
                 bar.get_height() + 30, str(val), ha="center", fontweight="bold")

# second plot looks at word count by class — fake postings tend to be shorter
df["word_count"] = df["combined_text"].str.split().str.len()
for label, color, name in [(0, "#4C9BE8", "Legitimate"), (1, "#E8654C", "Fraudulent")]:
    subset = df[df["fraudulent"] == label]["word_count"]
    axes[1].hist(subset, bins=60, alpha=0.6, color=color, label=name)
axes[1].set_xlabel("Word Count")
axes[1].set_ylabel("Frequency")
axes[1].set_title("Text Length by Class")
axes[1].legend()
axes[1].set_xlim(0, 1500)

plt.tight_layout()
plt.savefig("eda_plots.png", dpi=150)
plt.show()


# --- BASELINE: TF-IDF + Logistic Regression ---
# this is the simplest model, basically just counting words and seeing which ones
# show up more in fake vs real postings. good starting point before using transformers
print("\n" + "="*60)
print("BASELINE: TF-IDF + Logistic Regression")
print("="*60)

# turning the raw text into numbers using tfidf
# using bigrams too (ngram_range=(1,2)) so it can pick up on two-word phrases
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1, 2), sublinear_tf=True)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

# class_weight balanced is important here bc Ihave way more real jobs than fake ones
# without it the model would probably just predict real for everything
baseline_model = LogisticRegression(max_iter=1000, class_weight="balanced", C=1.0)
baseline_model.fit(X_train_tfidf, y_train)

# get predictions and probabilities for evaluation
y_pred_baseline = baseline_model.predict(X_test_tfidf)
y_prob_baseline = baseline_model.predict_proba(X_test_tfidf)[:, 1]

print(classification_report(y_test, y_pred_baseline, target_names=["Legitimate", "Fraudulent"]))
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_baseline):.4f}")


# --- SETUP FOR TRANSFORMER MODELS ---
# check if Ihave a gpu available, training on cpu is really slow
DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_NAME = "distilbert-base-uncased"
MAX_LEN    = 256    # truncating to 256 tokens to save memory, most posts fit in this
BATCH_SIZE = 16

print(f"\nUsing device: {DEVICE}")

# load the tokenizer that goes with distilbert
tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)


# pytorch dataset class — handles converting our text into token ids that the model can read
class JobPostingDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts     = list(texts)
        self.labels    = list(labels)
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # tokenize one example at a time, pad/truncate to max_len
        encoding = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids":      encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels":         torch.tensor(self.labels[idx], dtype=torch.long),
        }


# create the datasets and wrap them in dataloaders for batching
train_dataset = JobPostingDataset(X_train.values, y_train.values, tokenizer, MAX_LEN)
test_dataset  = JobPostingDataset(X_test.values,  y_test.values,  tokenizer, MAX_LEN)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False)


# helper function to run the model on test data and get back predictions
# Iuse no_grad here bc Idont need to compute gradients during evaluation
def get_predictions(model, loader, device):
    model.eval()
    all_labels, all_preds, all_probs = [], [], []

    with torch.no_grad():
        for batch in loader:
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            probs   = torch.softmax(outputs.logits, dim=-1)[:, 1].cpu().numpy()
            preds   = outputs.logits.argmax(dim=-1).cpu().numpy()

            all_labels.extend(batch["labels"].numpy())
            all_preds.extend(preds)
            all_probs.extend(probs)

    return np.array(all_labels), np.array(all_preds), np.array(all_probs)


# prints out all the metrics Icare about and returns them as a dict
# so Ican compare models at the end
def print_metrics(model_name, y_true, y_pred, y_prob):
    print(f"\n{'='*60}\n  {model_name}\n{'='*60}")
    print(classification_report(y_true, y_pred, target_names=["Legitimate", "Fraudulent"]))
    print(f"ROC-AUC: {roc_auc_score(y_true, y_prob):.4f}")

    p, r, f, _ = precision_recall_fscore_support(y_true, y_pred, average="binary")
    return {
        "accuracy":  accuracy_score(y_true, y_pred),
        "roc_auc":   roc_auc_score(y_true, y_prob),
        "precision": p,
        "recall":    r,
        "f1":        f,
    }


# --- APPROACH A: Fine-tuning DistilBERT ---
# instead of training from scratch Iload pretrained weights and keep training
# on our specific dataset — this is called fine tuning
print("\n" + "="*60)
print("APPROACH A: Fine-tuning DistilBERT")
print("="*60)

# loads distilbert with a classification layer added on top for 2 classes
model_ft = DistilBertForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=2
).to(DEVICE)

# since the dataset is really imbalanced Iweight the loss so the model
# gets penalized more for missing a fraudulent post than a real one
class_counts  = np.bincount(y_train.values)
class_weights = torch.tensor([1 / class_counts[0], 1 / class_counts[1]], dtype=torch.float).to(DEVICE)
loss_fn       = torch.nn.CrossEntropyLoss(weight=class_weights)

# adamw is the standard optimizer for transformers, lr of 2e-5 is pretty typical for finetuning
EPOCHS        = 3
LEARNING_RATE = 2e-5
optimizer     = AdamW(model_ft.parameters(), lr=LEARNING_RATE, weight_decay=0.01)
total_steps   = len(train_loader) * EPOCHS

# linear warmup scheduler — slowly increases lr at first then decreases it
# this help stabilize training especially at the beginning
scheduler     = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps,
)

# main training loop, one full pass through the data per epoch
for epoch in range(EPOCHS):
    model_ft.train()
    total_loss = 0

    for step, batch in enumerate(train_loader):
        input_ids      = batch["input_ids"].to(DEVICE)
        attention_mask = batch["attention_mask"].to(DEVICE)
        labels         = batch["labels"].to(DEVICE)

        optimizer.zero_grad()
        outputs = model_ft(input_ids=input_ids, attention_mask=attention_mask)
        loss    = loss_fn(outputs.logits, labels)
        loss.backward()

        # gradient clipping to prevent exploding gradients
        torch.nn.utils.clip_grad_norm_(model_ft.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()

        # print progress every 100 steps so Ican see its actually training
        if (step + 1) % 100 == 0:
            print(f"  Epoch {epoch+1}/{EPOCHS}  "
                  f"Step {step+1}/{len(train_loader)}  "
                  f"Loss: {total_loss / (step+1):.4f}")

    print(f"  → Epoch {epoch+1} complete. Avg loss: {total_loss / len(train_loader):.4f}")

# evaluate on the test set
y_true_ft, y_pred_ft, y_prob_ft = get_predictions(model_ft, test_loader, DEVICE)
ft_scores = print_metrics("Approach A: Fine-tuned DistilBERT", y_true_ft, y_pred_ft, y_prob_ft)

# save the model so Idont have to retrain it if Ineed to use it again
model_ft.save_pretrained("distilbert_finetuned")
tokenizer.save_pretrained("distilbert_finetuned")
print("\nFine-tuned model saved to ./distilbert_finetuned")


# --- APPROACH B: DistilBERT as a Feature Extractor ---
# here Idont fine tune anything — Ijust use distilbert to get embeddings
# and then train a simple logistic regression on top of those embeddings
print("\n" + "="*60)
print("APPROACH B: DistilBERT as Feature Extractor + Logistic Regression")
print("="*60)

# load distilbert without the classification head, weights are frozen (not updated)
feature_extractor = DistilBertModel.from_pretrained(MODEL_NAME).to(DEVICE)
feature_extractor.eval()


# for each batch Igrab the [CLS] token embedding (first token in the sequence)
# the cls token is basically a summary of the whole input — 768 numbers per posting
def extract_embeddings(loader, model, device):
    all_embeddings, all_labels = [], []

    with torch.no_grad():
        for batch in loader:
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            outputs       = model(input_ids=input_ids, attention_mask=attention_mask)
            cls_embedding = outputs.last_hidden_state[:, 0, :]  # index 0 = CLS token

            all_embeddings.append(cls_embedding.cpu().numpy())
            all_labels.extend(batch["labels"].numpy())

    return np.vstack(all_embeddings), np.array(all_labels)


print("Extracting embeddings for training set...")
X_train_emb, y_train_emb = extract_embeddings(train_loader, feature_extractor, DEVICE)

print("Extracting embeddings for test set...")
X_test_emb, y_test_emb   = extract_embeddings(test_loader,  feature_extractor, DEVICE)

# should be (num_samples, 768)
print(f"Embedding shape: {X_train_emb.shape}")

# now just train a regular logistic regression on these embeddings
lr_on_embeddings = LogisticRegression(max_iter=1000, class_weight="balanced", C=1.0)
lr_on_embeddings.fit(X_train_emb, y_train_emb)

y_pred_emb = lr_on_embeddings.predict(X_test_emb)
y_prob_emb = lr_on_embeddings.predict_proba(X_test_emb)[:, 1]

emb_scores = print_metrics(
    "Approach B: DistilBERT Features + Logistic Regression",
    y_test_emb, y_pred_emb, y_prob_emb
)


# --- RESULTS COMPARISON ---
# put all three models results into one dataframe so its easy to compare
print("\n" + "="*60)
print("RESULTS SUMMARY")
print("="*60)

# compute baseline scores in the same format as the other two
p, r, f, _ = precision_recall_fscore_support(y_test, y_pred_baseline, average="binary")
baseline_scores = {
    "accuracy":  accuracy_score(y_test, y_pred_baseline),
    "roc_auc":   roc_auc_score(y_test, y_prob_baseline),
    "precision": p,
    "recall":    r,
    "f1":        f,
}

results = pd.DataFrame({
    "Baseline (TF-IDF + LR)":         baseline_scores,
    "Approach A (Fine-tuned BERT)":    ft_scores,
    "Approach B (BERT Features + LR)": emb_scores,
}).T.round(4)

print(results.to_string())


# --- PLOTS ---
# bar chart comparing all three models on each metric
metrics = ["accuracy", "roc_auc", "precision", "recall", "f1"]
colors  = ["#4C9BE8", "#E8654C", "#52C47E"]

fig, axes = plt.subplots(1, len(metrics), figsize=(18, 5))
for ax, metric in zip(axes, metrics):
    values = results[metric].values
    labels = results.index.tolist()
    bars   = ax.bar(labels, values, color=colors)
    ax.set_ylim(0, 1.1)
    ax.set_title(metric.replace("_", " ").title(), fontweight="bold")
    ax.set_ylabel("Score")
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.01, f"{val:.3f}", ha="center", fontsize=8)
    ax.set_xticklabels(labels, rotation=15, ha="right", fontsize=7)

plt.suptitle("Model Comparison – Fake Job Posting Detection", fontweight="bold", fontsize=13)
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150)
plt.show()

# confusion matrices for all three so Ican see where each model is making mistakes
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
model_results = [
    ("Baseline (TF-IDF + LR)",         y_test,     y_pred_baseline),
    ("Approach A (Fine-tuned BERT)",    y_true_ft,  y_pred_ft),
    ("Approach B (BERT Features + LR)", y_test_emb, y_pred_emb),
]
for ax, (name, y_true, y_pred) in zip(axes, model_results):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax,
                xticklabels=["Legit", "Fraud"],
                yticklabels=["Legit", "Fraud"])
    ax.set_title(name, fontsize=9)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.tight_layout()
plt.savefig("confusion_matrices.png", dpi=150)
plt.show()

print("\nAll done! Saved: eda_plots.png | model_comparison.png | confusion_matrices.png")